include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - avoid_bool_literals_in_conditional_expressions
    - avoid_empty_else
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - cancel_subscriptions
    - constant_identifier_names
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - prefer_single_quotes
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_key_in_widget_constructors
